-- village_villagers.lua
--
-- Populates Cuberite's villages with villagers.
--
-- The engine places village blocks and stops there: "Villager" does not appear anywhere in
-- src/Generating/, and the prefab format cannot carry entities anyway (a cubeset encodes
-- only BLOCKTYPE plus NIBBLETYPE, and cSchematicFileSerializer drops TileEntities on both
-- load and save). So a village generated by Cuberite has buildings, farms, chests and no
-- villagers at all. This module adds them. (VillagerTrade's village_life.lua had the same
-- feature and removed it, with the note that it was to move to a separate plugin.)
--
-- It cannot know which pieces were placed - that would mean replicating the connector
-- matching - so it works from what it can compute exactly: the village's origin, which
-- structure_locate.lua predicts and confirms with the same biome test the engine uses.
-- Villagers are therefore placed on plausible village floors near the origin rather than
-- one per building the way vanilla does it.
--
-- Two hooks, split by cost:
--
--   HOOK_CHUNK_AVAILABLE runs inside cChunkMap::SetChunkData, which itself runs as a queued
--   task of cWorld::TickQueuedTasks. Nothing heavy belongs there, and nothing that touches
--   the world does either, so this hook only asks the cheap question - could this chunk hold
--   a village origin? - and queues the origin if so. That question is pure arithmetic: one
--   to four grid cells, two IntNoise2DInt calls each.
--
--   HOOK_WORLD_TICK then does the expensive part outside any chunk-map call stack, a couple
--   of origins per tick so a chunk-loading storm cannot stall the tick thread. The 256-column
--   pool test, the floor scan and the spawns all happen here. This is also what
--   VillagerTrade's village_life.lua does, and for the same reason.
--
-- The hook fires for chunks loaded from disk as well as freshly generated ones, so a
-- "already populated" flag would spawn a fresh batch on every restart. The guard is instead
-- a count: ForEachEntityInBox around the origin, and only the deficit up to PerVillage is
-- spawned, which makes a repeat run a no-op.

-- luacheck: globals StructureLocate mtVillager

VillageVillagers = {}

---How many villagers a village should end up with. Overridable from settings.ini.
VillageVillagers.PerVillage = 6

---How many queued origins to process per world tick.
VillageVillagers.OriginsPerTick = 2

local CHUNK_W = 16

---Walkable surfaces the village cubesets actually build. Villagers are only put on these,
---so they do not end up standing on the surrounding terrain, and only where both blocks
---above are air.
local FLOOR_BLOCKS =
{
	[E_BLOCK_PLANKS]       = true,
	[E_BLOCK_COBBLESTONE]  = true,
	[E_BLOCK_GRAVEL]       = true,  -- the paths
	[E_BLOCK_SANDSTONE]    = true,
	[E_BLOCK_STONE_BRICKS] = true,
	[E_BLOCK_LOG]          = true,
	[E_BLOCK_HAY_BALE]     = true,
}

---How far around the origin to look for villagers that are already there, and to place new
---ones. Villages span more ground than this, but staying near the origin keeps one decision
---per village instead of one per chunk of its bounding box.
local SPAWN_RADIUS = 48

---Vertical window searched for a floor. Villages sit on the surface, and Cuberite's sea
---level is 62 in the worlds shipped here.
local MIN_Y = 58
local MAX_Y = 86

---Chunks scanned for floors, the origin's first. Enough to find a few spots even when the
---origin itself landed inside a hill.
local SCAN_CHUNKS =
{
	{ 0, 0 }, { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 },
	{ 1, 1 }, { -1, 1 }, { 1, -1 }, { -1, -1 },
}

---Per-world placement parameters, or false when the world has no villages at all.
local ConfigCache = {}

---Origins queued by the chunk hook, oldest first. Head is the index of the oldest entry.
local Pending, Head = {}, 1

---Distinct origins queued right now, so a chunk that unloads and comes back is not queued
---twice before it is processed.
local Queued = {}

---Village origins already dealt with in this session, so an origin is only populated once.
---The population count below is what makes it restart-safe; this is just to avoid repeating
---the work while the server is up.
local Handled = {}

local function KeyOf(World, OriginX, OriginZ)
	return World:GetName() .. "|" .. OriginX .. "," .. OriginZ
end

local function GetConfig(World)
	local Name = World:GetName()
	local Cached = ConfigCache[Name]
	if (Cached == nil) then
		Cached = StructureLocate.GetConfig(World, StructureLocate.Kinds.Village) or false
		ConfigCache[Name] = Cached
	end
	if (Cached == false) then
		return nil
	end
	return Cached
end

---Queues an origin by world NAME, not by the world object. tolua hands each hook call its
---own userdata for the same cWorld, so comparing two of them with == is always false and the
---queue would silently never be drained.
local function Queue(World, OriginX, OriginZ)
	local Key = KeyOf(World, OriginX, OriginZ)
	if Queued[Key] or Handled[Key] then
		return
	end
	Queued[Key] = true
	Pending[#Pending + 1] = { WorldName = World:GetName(), OriginX = OriginX, OriginZ = OriginZ }
end

---Drops queued origins that have not been processed yet. Exposed because it is the right
---thing to do when a world goes away, and because it keeps tests independent.
function VillageVillagers.ClearQueue()
	Pending, Head, Queued = {}, 1, {}
end

---How many origins are waiting. For diagnostics.
---@return number
function VillageVillagers.PendingCount()
	local Count = 0
	for i = Head, #Pending do
		if (Pending[i] ~= nil) then
			Count = Count + 1
		end
	end
	return Count
end

---Number of villagers already within SPAWN_RADIUS of the origin.
local function CountVillagers(World, OriginX, OriginZ)
	local Box = cBoundingBox(
		Vector3d(OriginX - SPAWN_RADIUS, 0, OriginZ - SPAWN_RADIUS),
		Vector3d(OriginX + SPAWN_RADIUS, 255, OriginZ + SPAWN_RADIUS)
	)
	local Count = 0
	World:ForEachEntityInBox(Box, function(Entity)
		local Monster = tolua.cast(Entity, "cMonster")
		if (Monster ~= nil) and (Monster:GetMobType() == mtVillager) then
			Count = Count + 1
		end
		return false
	end)
	return Count
end

---Collects floor positions in one chunk where a villager can stand, in a stable order.
local function FindSpots(World, BlockX, BlockZ)
	local Spots = {}
	for z = 0, 15 do
		for x = 0, 15 do
			local wx, wz = BlockX + x, BlockZ + z
			for y = MAX_Y, MIN_Y, -1 do
				if FLOOR_BLOCKS[World:GetBlock(Vector3i(wx, y, wz))] then
					-- The floor is at y, so the villager stands at y + 1:
					if (World:GetBlock(Vector3i(wx, y + 1, wz)) == E_BLOCK_AIR)
						and (World:GetBlock(Vector3i(wx, y + 2, wz)) == E_BLOCK_AIR)
					then
						Spots[#Spots + 1] = { X = wx, Y = y + 1, Z = wz }
					end
					break
				end
			end
		end
	end
	return Spots
end

---Evenly spaced picks out of a list, so a batch does not all land in one corner.
local function Spread(List, Count)
	local Picked = {}
	if (#List == 0) or (Count <= 0) then
		return Picked
	end
	local Want = math.min(Count, #List)
	for i = 1, Want do
		Picked[#Picked + 1] = List[math.floor((i - 1) * #List / Want) + 1]
	end
	return Picked
end

---Brings one village up to PerVillage. Runs on the tick thread, outside the chunk-map stack.
local function Populate(WorldName, OriginX, OriginZ)
	local World = cRoot:Get():GetWorld(WorldName)
	if (World == nil) then
		return
	end
	if Handled[WorldName .. "|" .. OriginX .. "," .. OriginZ] then
		return
	end
	-- The origin chunk must still be loaded. GetBiomeAt answers -1 for a chunk that is not
	-- in the world, which is also the cheapest loaded-chunk test there is.
	if (World:GetBiomeAt(OriginX, OriginZ) < 0) then
		return
	end

	-- Confirm it really is a village: the chunk is loaded now, so the 256-column biome test
	-- that has to answer "unknown" during generation can be answered here.
	local Result = StructureLocate.Locate(World, "Village",
		math.floor(OriginX / CHUNK_W) * CHUNK_W + CHUNK_W / 2,
		math.floor(OriginZ / CHUNK_W) * CHUNK_W + CHUNK_W / 2, 0)
	if (Result == nil) or (not Result.Confirmed) or (Result.OriginX ~= OriginX)
		or (Result.OriginZ ~= OriginZ)
	then
		return
	end

	Handled[WorldName .. "|" .. OriginX .. "," .. OriginZ] = true

	local Deficit = VillageVillagers.PerVillage - CountVillagers(World, OriginX, OriginZ)
	if (Deficit <= 0) then
		return
	end

	for _, Offset in ipairs(SCAN_CHUNKS) do
		local BaseX, BaseZ = (math.floor(OriginX / CHUNK_W) + Offset[1]) * CHUNK_W,
			(math.floor(OriginZ / CHUNK_W) + Offset[2]) * CHUNK_W
		-- Never spawn into a chunk that is not loaded: a mob that ends up detached from a
		-- chunk still ticks, and when it is later destroyed the engine's
		-- VERIFY(a_World.RemoveEntity(*this)) aborts the whole server.
		if (World:GetBiomeAt(BaseX, BaseZ) >= 0) then
			for _, Spot in ipairs(Spread(FindSpots(World, BaseX, BaseZ), Deficit)) do
				World:SpawnMob(Spot.X + 0.5, Spot.Y, Spot.Z + 0.5, mtVillager)
				Deficit = Deficit - 1
			end
		end
		if (Deficit <= 0) then
			break
		end
	end
end

---Handler for HOOK_CHUNK_AVAILABLE. Queues only; the world is not touched here.
---@param World cWorld
---@param ChunkX number
---@param ChunkZ number
---@return boolean
function VillageVillagers.OnChunkAvailable(World, ChunkX, ChunkZ)
	if not VillageVillagers.Enabled then
		return false
	end
	local Cfg = GetConfig(World)
	if (Cfg == nil) then
		return false
	end

	local BaseX, BaseZ = ChunkX * CHUNK_W, ChunkZ * CHUNK_W
	for _, Candidate in ipairs(StructureLocate.GetCandidates(Cfg, BaseX, BaseX + CHUNK_W - 1,
		BaseZ, BaseZ + CHUNK_W - 1))
	do
		if (Candidate.OriginX >= BaseX) and (Candidate.OriginX < BaseX + CHUNK_W)
			and (Candidate.OriginZ >= BaseZ) and (Candidate.OriginZ < BaseZ + CHUNK_W)
		then
			Queue(World, Candidate.OriginX, Candidate.OriginZ)
		end
	end
	return false
end

---Handler for HOOK_WORLD_TICK. Does the work the chunk hook deferred.
---@param World cWorld
---@param TimeDiff number
---@return boolean
function VillageVillagers.OnWorldTick(World, TimeDiff)
	if not VillageVillagers.Enabled then
		return false
	end
	local Name = World:GetName()
	local Budget = VillageVillagers.OriginsPerTick
	while (Budget > 0) do
		-- Find the oldest entry for this world; entries of other worlds wait for their own tick.
		local Index = nil
		for i = Head, #Pending do
			if (Pending[i] ~= nil) and (Pending[i].WorldName == Name) then
				Index = i
				break
			end
		end
		if (Index == nil) then
			break
		end
		local Item = Pending[Index]
		Pending[Index] = nil
		Queued[Name .. "|" .. Item.OriginX .. "," .. Item.OriginZ] = nil
		Budget = Budget - 1
		Populate(Item.WorldName, Item.OriginX, Item.OriginZ)
	end
	-- Compact once nothing is left:
	local Any = false
	for i = Head, #Pending do
		if (Pending[i] ~= nil) then
			Any = true
			break
		end
	end
	if not Any then
		Pending, Head = {}, 1
	end
	return false
end
